name: hasura_connect
description: Connect your Flutter/Dart apps to Hasura simply. All the power of GraphQL and Postgres in Flutter
version: 0.2.0
homepage: https://github.com/Flutterando/hasura_connect
author: Team Flutterando <jacobaraujo7@gmail.com>

dependencies:
  websocket: ^0.0.5
  http: ^0.12.0+2
  rxdart: ^0.22.6
  shared_preferences: ^0.5.4+5
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.1.0 <3.0.0'

