name: hasura_connect
description: Connect your Flutter/Dart apps to Hasura simply. All the power of GraphQL and Postgres in Flutter
version: 0.0.7+1
homepage: https://github.com/Flutterando/hasura_connect
author: Team Flutterando <jacobaraujo7@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

