name: hasura_connect
description: Connect your Flutter / Dart apps to Hasura simply.
version: 0.0.6
homepage: https://github.com/Flutterando/hasura_connect
author: Team Flutterando <jacobaraujo7@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  websocket: ^0.0.5


dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

