name: flutter_example
description: An app built using Flutter for web

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  hasura_connect: any

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

dependency_overrides:
  hasura_connect:
    git:
      url: https://github.com/Flutterando/hasura_connect
      ref: web
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui